language: java
jdk:
  - oraclejdk7
  - openjdk6
before_install:
  - export MAVEN_OPTS="-Xmx512M -XX:MaxPermSize=256M"
# Exclude e2e-tests
script: mvn clean install -pl common,cachingxslt,jeeves,sde,web-ui,web-ui-docs,domain,oaipmh,core,csw-server,harvesters,healthmonitor,services,web-client,wro4j,web
